#!/usr/bin/env bash
# Install the Personal Growth System as a desktop app on Linux.
#
# Idempotent: safe to re-run after `git pull`, which is how you update.
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(pwd)"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }
ok() { printf '  \033[32m✓\033[0m %s\n' "$*"; }

say "1/6  System packages"
# pywebview renders through the OS engine rather than bundling one. On Linux
# that is WebKitGTK plus the PyGObject bindings, both distro packages.
missing=()
python3 -c 'import gi' 2>/dev/null || missing+=(pygobject)
# Test what pywebview actually needs: the GObject-Introspection typelib, loaded
# the same way it will load it. Checking pkg-config instead would test for the
# *-devel* package, which supplies build headers nothing here uses — the
# runtime alone is enough and is what distros install by default.
python3 - <<'PY' 2>/dev/null || missing+=(webkit2gtk)
import gi
for version in ("4.1", "4.0"):
    try:
        gi.require_version("WebKit2", version)
        from gi.repository import WebKit2  # noqa: F401
        raise SystemExit(0)
    except (ValueError, ImportError):
        continue
raise SystemExit(1)
PY
if [ ${#missing[@]} -eq 0 ]; then
	ok "webkit2gtk and PyGObject present"
else
	warn "missing: ${missing[*]}"
	if command -v dnf >/dev/null; then
		echo "     sudo dnf install python3-gobject webkit2gtk4.1"
	elif command -v apt >/dev/null; then
		echo "     sudo apt install python3-gi gir1.2-webkit2-4.1"
	elif command -v pacman >/dev/null; then
		echo "     sudo pacman -S python-gobject webkit2gtk-4.1"
	fi
	echo "     (then re-run this script)"
	exit 1
fi

say "2/6  Python environment"
[ -d .venv ] || python3 -m venv .venv
.venv/bin/pip install -q --upgrade pip
.venv/bin/pip install -q -r backend/requirements.txt
ok "dependencies installed"

# The venv is isolated, so the *system* PyGObject is invisible to it. Expose
# just that path rather than turning on system-site-packages wholesale.
if .venv/bin/python -c 'import gi' 2>/dev/null; then
	ok "PyGObject visible"
else
	# Ask the system Python where `gi` actually is, rather than deriving it
	# from sysconfig: on Fedora sysconfig reports /usr/local/lib/... (the local
	# install prefix) while distro packages live in /usr/lib64/..., and the
	# same mismatch appears in different forms on Debian and Arch.
	GI_SITE="$(python3 -c 'import gi, os; print(os.path.dirname(os.path.dirname(os.path.abspath(gi.__file__))))')"
	VENV_SITE="$(.venv/bin/python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
	echo "$GI_SITE" >"$VENV_SITE/_system_gi.pth"
	if .venv/bin/python -c 'import gi' 2>/dev/null; then
		ok "system PyGObject linked in from $GI_SITE"
	else
		rm -f "$VENV_SITE/_system_gi.pth"
		warn "PyGObject not usable from the venv — the window will not open."
		warn "The app still works: run 'pgs --browser'."
	fi
fi

# Python version mismatch is the other way this fails, and it fails at import
# time with a confusing error rather than here.
SYS_PY="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
VENV_PY="$(.venv/bin/python -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
[ "$SYS_PY" = "$VENV_PY" ] || warn "venv is Python $VENV_PY but system PyGObject is built for $SYS_PY — delete .venv and re-run"

say "3/6  Data"
# The repo holds the app, not your practice, so `data/` is created here rather
# than arriving with the clone. The six researched trees are copied out of
# data/seed/ — once, and only into an empty directory.
#
# Deliberately not a sync, and deliberately not done at startup. A tree you
# deleted in the UI has to stay deleted, and one you have edited must never be
# reverted by re-running this script.
mkdir -p data/domains data/log
if [ -z "$(ls -A data/domains 2>/dev/null)" ]; then
	cp data/seed/*.toml data/domains/
	ok "seeded data/domains/ with $(find data/seed -name '*.toml' | wc -l) trees"
else
	ok "data/domains/ already has trees — left untouched"
fi

say "4/6  Frontend"
if [ ! -d frontend/node_modules ]; then (cd frontend && npm install --silent); fi
(cd frontend && npm run build >/dev/null)
ok "built to frontend/build"

say "5/6  Launcher"
BIN="$HOME/.local/bin"
APPS="$HOME/.local/share/applications"
mkdir -p "$BIN" "$APPS"

cat >"$BIN/pgs" <<EOF
#!/usr/bin/env bash
# Generated by install-linux.sh — re-run that script to regenerate.
exec "$ROOT/.venv/bin/python" "$ROOT/desktop.py" "\$@"
EOF
chmod +x "$BIN/pgs"
ok "$BIN/pgs"

cat >"$APPS/pgs.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Personal Growth System
Comment=Local tech tree for deliberate practice
Exec=$BIN/pgs
Icon=$ROOT/frontend/static/favicon.svg
Terminal=false
Categories=Education;Utility;
StartupWMClass=Personal Growth System
EOF
update-desktop-database "$APPS" 2>/dev/null || true
ok "$APPS/pgs.desktop"

say "6/6  Check"
.venv/bin/python -m pytest backend/tests -q 2>&1 | tail -1

cat <<EOF

Done. Launch from your app menu, or:

  pgs                                  native window, data in ./data
  pgs --data-dir /mnt/shared/pgs       shared with the other OS (see SYNC.md)
  pgs --browser                        no window, opens your browser

If ~/.local/bin is not on your PATH, add it to ~/.bashrc:
  export PATH="\$HOME/.local/bin:\$PATH"
EOF
