# Install the Personal Growth System as a desktop app on Windows.
#
#   powershell -ExecutionPolicy Bypass -File install-windows.ps1
#
# Idempotent: safe to re-run after `git pull`, which is how you update.
#
# Windows needs no display dependencies at all. pywebview renders through the
# Edge WebView2 runtime, which ships with Windows 10 and 11 — so unlike Linux
# there is nothing to install beyond Python, Node and the packages below.

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot
$Root = (Get-Location).Path

function Say  ($m) { Write-Host "`n$m" -ForegroundColor White }
function Ok   ($m) { Write-Host "  OK  $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  !   $m" -ForegroundColor Yellow }

Say "1/5  Prerequisites"
foreach ($exe in @("python", "npm")) {
    if (-not (Get-Command $exe -ErrorAction SilentlyContinue)) {
        throw "$exe is not on PATH. Install Python 3.11+ and Node 20+, then re-run."
    }
}
Ok ((python --version) + " / node " + (node --version))

# WebView2 is present on Windows 11 and on updated Windows 10, but check rather
# than let the window fail to open with no explanation.
$wv = Get-ItemProperty -ErrorAction SilentlyContinue `
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
if ($wv) { Ok "Edge WebView2 runtime present" }
else { Warn "Edge WebView2 not detected — if the window fails to open, install it from https://developer.microsoft.com/microsoft-edge/webview2/" }

Say "2/5  Python environment"
if (-not (Test-Path ".venv")) { python -m venv .venv }
& .\.venv\Scripts\python.exe -m pip install -q --upgrade pip
& .\.venv\Scripts\python.exe -m pip install -q -r backend\requirements.txt
Ok "dependencies installed"

Say "3/5  Frontend"
if (-not (Test-Path "frontend\node_modules")) {
    Push-Location frontend; npm install --silent; Pop-Location
}
Push-Location frontend; npm run build | Out-Null; Pop-Location
Ok "built to frontend\build"

Say "4/5  Launcher"
# A .vbs shim launches pythonw.exe with no console window flashing up.
$LauncherVbs = Join-Path $Root "pgs.vbs"
@"
' Generated by install-windows.ps1 — re-run that script to regenerate.
Set shell = CreateObject("WScript.Shell")
args = ""
For Each a In WScript.Arguments : args = args & " """ & a & """" : Next
shell.Run """$Root\.venv\Scripts\pythonw.exe"" ""$Root\desktop.py""" & args, 0, False
"@ | Set-Content -Encoding ASCII $LauncherVbs
Ok "pgs.vbs"

$StartMenu = [Environment]::GetFolderPath("Programs")
$Shortcut = Join-Path $StartMenu "Personal Growth System.lnk"
$ws = New-Object -ComObject WScript.Shell
$sc = $ws.CreateShortcut($Shortcut)
$sc.TargetPath = "wscript.exe"
$sc.Arguments = """$LauncherVbs"""
$sc.WorkingDirectory = $Root
$sc.Description = "Local tech tree for deliberate practice"
$icon = Join-Path $Root "frontend\static\favicon.ico"
if (Test-Path $icon) { $sc.IconLocation = $icon }
$sc.Save()
Ok $Shortcut

Say "5/5  Check"
& .\.venv\Scripts\python.exe -m pytest backend\tests -q 2>&1 | Select-Object -Last 1

Write-Host @"

Done. Launch from the Start Menu, or:

  .\.venv\Scripts\python.exe desktop.py
  .\.venv\Scripts\python.exe desktop.py --data-dir D:\pgs-data   (shared, see SYNC.md)
  .\.venv\Scripts\python.exe desktop.py --browser

"@ -ForegroundColor Cyan
