#!/usr/bin/env bash
# Install the Personal Growth System as a desktop app on Linux.
#
# Idempotent: safe to re-run after `git pull`, which is how you update.
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(pwd)"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }
ok() { printf '  \033[32m✓\033[0m %s\n' "$*"; }

say "1/5  System packages"
# pywebview renders through the OS engine rather than bundling one. On Linux
# that is WebKitGTK plus the PyGObject bindings, both distro packages.
missing=()
python3 -c 'import gi' 2>/dev/null || missing+=(pygobject)
pkg-config --exists webkit2gtk-4.1 2>/dev/null || pkg-config --exists webkit2gtk-4.0 2>/dev/null || missing+=(webkit2gtk)
if [ ${#missing[@]} -eq 0 ]; then
	ok "webkit2gtk and PyGObject present"
else
	warn "missing: ${missing[*]}"
	if command -v dnf >/dev/null; then
		echo "     sudo dnf install python3-gobject webkit2gtk4.1"
	elif command -v apt >/dev/null; then
		echo "     sudo apt install python3-gi gir1.2-webkit2-4.1"
	elif command -v pacman >/dev/null; then
		echo "     sudo pacman -S python-gobject webkit2gtk-4.1"
	fi
	echo "     (then re-run this script)"
	exit 1
fi

say "2/5  Python environment"
[ -d .venv ] || python3 -m venv .venv
.venv/bin/pip install -q --upgrade pip
.venv/bin/pip install -q -r backend/requirements.txt
ok "dependencies installed"

# The venv is isolated, so the *system* PyGObject is invisible to it. Expose
# just that path rather than turning on system-site-packages wholesale.
if ! .venv/bin/python -c 'import gi' 2>/dev/null; then
	SYS_SITE="$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
	SYS_SITE64="${SYS_SITE/lib\/python/lib64\/python}"
	VENV_SITE="$(.venv/bin/python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
	{ echo "$SYS_SITE"; [ -d "$SYS_SITE64" ] && echo "$SYS_SITE64"; } >"$VENV_SITE/_system_gi.pth"
	.venv/bin/python -c 'import gi' 2>/dev/null &&
		ok "system PyGObject linked into the venv" ||
		warn "PyGObject still not visible — the app will fall back to --browser"
else
	ok "PyGObject visible"
fi

say "3/5  Frontend"
if [ ! -d frontend/node_modules ]; then (cd frontend && npm install --silent); fi
(cd frontend && npm run build >/dev/null)
ok "built to frontend/build"

say "4/5  Launcher"
BIN="$HOME/.local/bin"
APPS="$HOME/.local/share/applications"
mkdir -p "$BIN" "$APPS"

cat >"$BIN/pgs" <<EOF
#!/usr/bin/env bash
# Generated by install-linux.sh — re-run that script to regenerate.
exec "$ROOT/.venv/bin/python" "$ROOT/desktop.py" "\$@"
EOF
chmod +x "$BIN/pgs"
ok "$BIN/pgs"

cat >"$APPS/pgs.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Personal Growth System
Comment=Local tech tree for deliberate practice
Exec=$BIN/pgs
Icon=$ROOT/frontend/static/favicon.png
Terminal=false
Categories=Education;Utility;
StartupWMClass=Personal Growth System
EOF
update-desktop-database "$APPS" 2>/dev/null || true
ok "$APPS/pgs.desktop"

say "5/5  Check"
.venv/bin/python -m pytest backend/tests -q 2>&1 | tail -1

cat <<EOF

Done. Launch from your app menu, or:

  pgs                                  native window, data in ./data
  pgs --data-dir /mnt/shared/pgs       shared with the other OS (see SYNC.md)
  pgs --browser                        no window, opens your browser

If ~/.local/bin is not on your PATH, add it to ~/.bashrc:
  export PATH="\$HOME/.local/bin:\$PATH"
EOF
