#!/usr/bin/env python3
"""Build a throwaway data directory that exercises nearly every screen.

Why this exists
---------------
The alternative was reading the user's own log, and that is a refusal — see the
second bullet of CLAUDE.md's `## Never`. A journal is not sample data. But UI
work genuinely needs data with the shapes real use produces: a day carrying
five photographs, a chapter spanning three months, a folder that was renamed, a
reminder that came due and was answered. Inventing those one at a time inside a
test is how somebody ends up opening the real file "just to see the shape".

So the fixture is a program rather than a directory of committed JSONL, and the
three reasons are worth stating because they decide what may be changed here:

 - **It writes through the app's own code.** Log lines come from
   `capture/eventlog.append`, media from `media.write_stream`. The fixture
   therefore cannot drift away from the format the way a copied file silently
   would: add a field to an event and this script either keeps emitting valid
   data or stops running, and both of those are better than emitting last
   month's shape without saying so.
 - **Nothing shaped like a journal enters the repo.** What is version
   controlled is the generator. A `.jsonl` of plausible sentences sitting in
   `git log` for good is precisely the failure this arrangement exists to
   prevent, and "but they were invented" is not a distinction anyone makes
   reliably at a glance six months later.
 - **It is anchored on today.** Due reminders and "this month" are relative, so
   a fixture pinned to a fixed date stops exercising the screens that matter
   within about a week. `--anchor` pins it when a reproducible run is wanted.

Everything below is invented — a workshop, a garden, a short film, some
reading. None of it is anybody's.

    python scripts/fixture.py                     # → data.fixture/
    python desktop.py --data-dir data.fixture     # ...and look at it

`data.fixture/` is already gitignored, by the `data.*/` rule that covers a data
directory left behind after a move.

What it does not cover
----------------------
The `.mp4` is not a playable video. Encoding one needs ffmpeg, which this repo
deliberately does not depend on (`media.py` says why), so the file is a
placeholder carrying a real poster frame. The video *tile*, its badge and its
poster are therefore exercised everywhere they appear; pressing play is not.
"""
from __future__ import annotations

import argparse
import asyncio
import io
import os
import shutil
import sys
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# A directory this script made, and the only kind it will overwrite. The check
# is the same shape as `config.check_data_dir`'s and `backup.sh`'s: a refusal
# that costs nothing when you meant it and everything when you did not. Real
# data carries no marker, so `--out data` cannot be talked into running.
MARKER = ".fixture"


# ── Refusals ──────────────────────────────────────────────────────────────


def resolve_target(raw: str, force: bool) -> Path:
    target = Path(raw).expanduser().resolve()

    if target == (ROOT / "data").resolve():
        raise SystemExit(
            f"refusing to write the fixture into {target} — that is the live "
            f"data directory. Pick another name; `data.fixture` is gitignored."
        )
    if target.parent == target:
        raise SystemExit(f"refusing to write the fixture to {target}")

    if target.exists():
        if not target.is_dir():
            raise SystemExit(f"{target} exists and is not a directory")
        if not (target / MARKER).exists():
            raise SystemExit(
                f"{target} exists and was not made by this script (no {MARKER} "
                f"in it). Refusing to touch it — if it really is disposable, "
                f"delete it yourself first."
            )
        if not force:
            raise SystemExit(
                f"{target} is an existing fixture. Pass --force to rebuild it "
                f"from scratch."
            )
        shutil.rmtree(target)

    target.mkdir(parents=True)
    (target / MARKER).write_text(
        "Generated by scripts/fixture.py. Disposable: delete it whenever.\n",
        encoding="utf-8",
    )
    return target


# ── Media ─────────────────────────────────────────────────────────────────


def _tile(index: int, width: int, height: int) -> bytes:
    """A PNG that is easy to tell from the one beside it.

    Drawn rather than shipped, so the repo carries no images at all: a set of
    committed stand-in photographs would be indistinguishable at a glance from
    a set of committed real ones, which is the confusion this whole file exists
    to avoid. A diagonal ramp, a hue per index, and the index itself in the
    corner — enough to see that a mosaic put the right tile in the right slot,
    and obviously not a photograph.
    """
    from PIL import Image, ImageDraw

    # A cheap spread around the wheel; adjacent indices never share a hue.
    hue = (index * 47) % 360
    image = Image.new("HSV", (width, height))
    pixels = image.load()
    for y in range(height):
        for x in range(width):
            ramp = (x / width + y / height) / 2
            pixels[x, y] = (hue // 2, 150, int(60 + 150 * ramp))
    image = image.convert("RGB")

    # The default bitmap font is tiny, and its size argument is not available
    # on every Pillow this repo will meet, so the label is drawn small and
    # scaled up. Nearest-neighbour on purpose: crisp blocks read better at a
    # distance than a smoothed smear.
    label = Image.new("RGB", (24, 12), (0, 0, 0))
    ImageDraw.Draw(label).text((2, 1), f"{index:02d}", fill=(255, 255, 255))
    scale = max(2, min(width, height) // 24)
    label = label.resize((24 * scale, 12 * scale), Image.NEAREST)
    image.paste(label, (scale * 2, scale * 2))

    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def _write_blob(blobs, data: bytes, day: str, filename: str, folder: str) -> str:
    """One upload, through the real blob store rather than beside it.

    `write_stream` is async because it consumes an upload chunk by chunk, and
    it owns the on-disk naming convention. Going through it here — instead of
    dropping a file into `media/YYYY-MM/` by hand — is what keeps the fixture's
    filenames the same shape as a real upload's after somebody changes that
    convention.
    """

    async def _run() -> tuple[str, int]:
        async def chunks():
            yield data

        return await blobs.write_stream(
            chunks(), day=day, filename=filename, expected=len(data), folder=folder
        )

    ref, _ = asyncio.run(_run())
    return ref


# ── The build ─────────────────────────────────────────────────────────────


def build(target: Path, anchor_day: str) -> dict:
    from backend.app import config
    from backend.app import media as blobs
    from backend.app.timeutil import TZ
    from backend.capture import eventlog as capture_log
    from backend.capture.colors import FOLDER_PALETTE
    from backend.capture.store import Store

    config.ensure_dirs()
    anchor = datetime.strptime(anchor_day, "%Y-%m-%d").date()

    def day(offset: int) -> str:
        """`day(-3)` is three days before the anchor. Offsets are never
        positive — everything in a log has already happened."""
        return (anchor + timedelta(days=offset)).strftime("%Y-%m-%d")

    def stamp(offset: int, hour: int = 9, minute: int = 0) -> str:
        when = datetime.combine(anchor + timedelta(days=offset), datetime.min.time())
        return when.replace(hour=hour, minute=minute, tzinfo=TZ).isoformat(
            timespec="seconds"
        )

    tally: dict[str, int] = {}

    # ── media ─────────────────────────────────────────────────────────────
    #
    # Aspect ratios on purpose: the mosaic lays out by shape, so a fixture of
    # twelve identical squares would make every arrangement look correct.
    shapes = [
        (-64, 1200, 800, "workshop"),
        (-64, 800, 1200, "workshop"),
        (-63, 1000, 1000, "workshop"),
        (-48, 1600, 600, "garden"),
        (-47, 900, 1200, "garden"),
        (-47, 1200, 900, "garden"),
        (-46, 1200, 900, "garden"),
        (-30, 1400, 900, "short film"),
        (-30, 900, 1400, "short film"),
        (-12, 1200, 800, "workshop"),
        (-11, 1000, 1000, ""),
        (-2, 1300, 900, "garden"),
        (-1, 900, 1200, "garden"),
    ]
    shots = []
    for i, (offset, width, height, folder_name) in enumerate(shapes):
        ref = _write_blob(
            blobs, _tile(i, width, height), day(offset), f"shot-{i}.png", folder_name
        )
        blobs.derive_view(ref)
        shots.append(ref)

    # The video: a placeholder file with a real poster. See the module
    # docstring — the tile renders, the play button does not.
    clip = _write_blob(
        blobs, b"\x00\x00\x00\x18ftypmp42" + b"\x00" * 512,
        day(-30), "clip.mp4", "short film",
    )
    blobs.save_poster(clip, _tile(99, 1280, 720))
    tally["media"] = len(shots) + 1

    # ── capture ───────────────────────────────────────────────────────────
    #
    # Written as raw log events rather than through `Store`, for one reason:
    # `Store.capture` stamps `ts` from the clock and has no backdating hook —
    # deliberately, since `import_csv` is the only caller with a right to one.
    # A journal that all happened in the same second is not a journal, so the
    # events go in directly and the index is rebuilt from them at the end,
    # which is the path a fresh launch takes anyway.
    folders: dict[str, str] = {}

    def folder(key: str, name: str, tags: list[str], offset: int) -> str:
        folder_id = capture_log.new_id()
        colour = FOLDER_PALETTE[len(folders) % len(FOLDER_PALETTE)]
        capture_log.append(
            capture_log.CREATE_FOLDER, folder_id, text=name, color=colour,
            day=day(offset), ts=stamp(offset, 8),
        )
        for tag in tags:
            capture_log.append(
                capture_log.MAP_TAG, folder_id, tag=tag,
                day=day(offset), ts=stamp(offset, 8, 1),
            )
        folders[key] = folder_id
        return folder_id

    workshop = folder("workshop", "Workshop", ["workshop", "bench"], -70)
    garden = folder("garden", "Allotment", ["garden", "seedlings"], -70)
    film = folder("film", "Short film", ["film", "edit"], -70)
    reading = folder("reading", "Reading", ["reading"], -69)
    scratch = folder("scratch", "Scratch", ["scratch"], -60)

    # Renamed, so `folder_names` carries a history and an `--allotment`
    # directive written months ago still files where it always did.
    capture_log.append(
        capture_log.RENAME_FOLDER, garden, text="Garden", day=day(-40), ts=stamp(-40, 8)
    )
    # Deleted, so the fold has a folder that is gone and entries that are not.
    capture_log.append(
        capture_log.DELETE_FOLDER, scratch, day=day(-55), ts=stamp(-55, 8)
    )

    capture_log.append(
        capture_log.SET_STATE, workshop, text="active", day=day(-68), ts=stamp(-68, 8)
    )
    capture_log.append(
        capture_log.SET_STATE, film, text="shipped", day=day(-20), ts=stamp(-20, 8)
    )
    capture_log.append(
        capture_log.SET_OVERVIEW, workshop,
        text="Hand tools only, and finishing what is already on the bench before "
             "starting anything else.",
        day=day(-68), ts=stamp(-68, 8, 2),
    )
    capture_log.append(
        capture_log.SET_OVERVIEW_MEDIA, workshop, text=shots[0],
        day=day(-63), ts=stamp(-63, 18),
    )

    # The shelf: two headings, one of them renamed, and an explicit order. A
    # third folder is left ungrouped, so the loose grid above the headings is
    # not empty either.
    year = anchor.strftime("%Y")
    for folder_id, group, offset in (
        (workshop, "Making", -66),
        (garden, "Making", -66),
        (film, "Finished", -21),
    ):
        capture_log.append(
            capture_log.SET_GROUP, folder_id, text=group, year=year,
            day=day(offset), ts=stamp(offset, 8, 3),
        )
    capture_log.append(
        capture_log.RENAME_GROUP, "Finished", text="Shipped", year=year,
        day=day(-19), ts=stamp(-19, 8),
    )
    capture_log.append(
        capture_log.ORDER_GROUPS, year, order=["Shipped", "Making"], year=year,
        day=day(-18), ts=stamp(-18, 8),
    )

    # A chapter named by hand, anchored to the month its run began in.
    chapter_month = anchor - timedelta(days=64)
    capture_log.append(
        capture_log.NAME_CHAPTER, workshop, text="The long bench",
        year=chapter_month.strftime("%Y"), month=chapter_month.month,
        day=day(-60), ts=stamp(-60, 8),
    )

    # Lifted: `<garden>` reads as `garden` everywhere and files exactly as it
    # did. Only a tag can be lifted, which is why nothing else here is.
    capture_log.append(capture_log.LIFT_TAG, "garden", day=day(-35), ts=stamp(-35, 8))

    entries: list[str] = []

    def capture(offset: int, hour: int, text: str, media=(), reply_to=None) -> str:
        entry_id = capture_log.new_id()
        capture_log.append(
            capture_log.CAPTURE, entry_id, text=text, day=day(offset),
            ts=stamp(offset, hour), media=list(media), reply_to=reply_to,
        )
        entries.append(entry_id)
        return entry_id

    # Every token the syntax bar knows, and the three things that look like
    # tokens and are not: a quoted string, an email address and an escaped
    # backslash. Those three are the corpus's own boundary cases, and the ones
    # a rewritten tokenizer breaks first.
    capture(-70, 9, "Cleared the bench. Everything on it belongs to something unfinished.")
    capture(-70, 14, "<workshop> squared the vice jaws, finally")
    capture(-69, 8, "\\pleased with the first drawer that closed by itself")
    capture(-68, 11, "<bench> @garage sharpening session, twenty minutes, no music")
    capture(-67, 19, 'Wrote "a note about <tags>" and none of it should tokenize')
    capture(-66, 9, "Mail from a@b.com about the timber order — not a place")
    capture(-65, 16, "Backslash on its own: \\ and that is all it is")
    capture(
        -64, 10, "<workshop> {q3} the cabinet, if it is going to happen at all",
        media=shots[0:2],
    )
    capture(-64, 17, "@helsinki hardware shop had the hinges after all", media=[shots[2]])
    capture(-63, 12, "<仕事> a tag nobody has mapped yet")

    capture(-56, 9, "--scratch filing this into a folder that gets deleted later")
    capture(-48, 7, "<garden> first seedlings in, three weeks late", media=[shots[3]])
    capture(-47, 18, "<seedlings> thinned the rows", media=shots[4:7])
    capture(-46, 8, '--"short film" \\frustrated location scouting, nothing usable')
    capture(-40, 9, "--allotment the directive still resolves after the rename")

    due = capture(-30, 11, "<film> rough cut done {tmr} watch it again cold", media=[clip])
    capture(-30, 15, "<edit> colour pass, one scene", media=shots[7:9])
    dismissed = capture(-10, 9, "<workshop> order the brass screws {3d}")
    # Three reminders, and all three states of one: dismissed above, still in
    # the future below, and this one standing — come due and not yet dealt
    # with, which is the only state that puts the banner on screen at all.
    capture(-5, 9, "<bench> flatten the sole of the No.7 {2d}")
    capture(-3, 8, "<garden> mulch before the frost {2w}")

    capture(
        -22, 20,
        "A long one, because the feed has to hold a paragraph as well as a line. "
        "The point of the cap in config.py is that this is an entry rather than a "
        "document — three thousand words is the ceiling and nothing in ordinary "
        "use comes near it, which is what makes the ceiling safe to have. What "
        "the log actually fills up with is this: a few sentences, written once, "
        "never edited, and read back months later in a feed of days.",
    )

    # Todos, kept well under `MAX_OPEN_TODOS` — the cap is enforced on the write
    # in `Store.capture`, and this file goes round that, so it has to respect it
    # by hand or the fixture would encode a state the app cannot reach.
    todo_one = capture(-12, 9, "--todo return the clamps", media=[shots[9]])
    todo_many = capture(
        -11, 10,
        "workshop list\n--todo buy 4mm dowel\n--todo re-glue the drawer\n"
        "--todo sharpen the No.4",
        media=[shots[10]],
    )
    capture(-2, 8, "--todo water the beds before Friday", media=[shots[11]])

    capture_log.append(capture_log.CHECK, todo_one, line=0, day=day(-9), ts=stamp(-9, 9))
    capture_log.append(capture_log.CHECK, todo_many, line=1, day=day(-8), ts=stamp(-8, 9))
    capture_log.append(capture_log.CHECK, todo_many, line=2, day=day(-7), ts=stamp(-7, 9))
    # Ticked and unticked again: a real double-toggle, which must keep file
    # order rather than being deduped away.
    capture_log.append(capture_log.UNCHECK, todo_many, line=2, day=day(-6), ts=stamp(-6, 9))

    # Filed by hand: no tag on the line, so this is the third route into a
    # folder. Then moved, because `assign` replaces rather than accumulates.
    plain = capture(-25, 13, "Finished the Sebald. Nothing to say about it yet.")
    capture_log.append(
        capture_log.ASSIGN, plain, folder=workshop, day=day(-25), ts=stamp(-25, 14)
    )
    capture_log.append(
        capture_log.ASSIGN, plain, folder=reading, day=day(-24), ts=stamp(-24, 9)
    )
    stray = capture(-23, 9, "Second-hand shop had the Rilke")
    capture_log.append(
        capture_log.ASSIGN, stray, folder=reading, day=day(-23), ts=stamp(-23, 10)
    )
    capture_log.append(
        capture_log.UNASSIGN, stray, folder=reading, day=day(-21), ts=stamp(-21, 9)
    )

    # A reminder answered, and a reminder simply dismissed. Answering writes
    # both halves — the reply carries the link, and the prompt it answers is
    # dismissed, because being asked again would be the app not listening.
    capture(-2, 21, "watched it cold and the second scene has to go", reply_to=due)
    capture_log.append(capture_log.DISMISS, due, line=0, day=day(-2), ts=stamp(-2, 21, 1))
    capture_log.append(
        capture_log.DISMISS, dismissed, line=0, day=day(-6), ts=stamp(-6, 12)
    )

    # Media and no words at all — a clip is a capture on its own.
    capture(-1, 17, "", media=[shots[12]])
    capture(0, 8, "<workshop> back at it")

    # Written out of order, on purpose. The fold sorts by `ts`, so this lands
    # in yesterday evening where it belongs rather than at the end of the file.
    capture(-1, 22, "\\tired but the joint finally closed")

    # A duplicated line, which a restored backup and an interrupted write both
    # produce. The fold is last-wins, so this must change nothing at all — and
    # the fixture is where that stays true by being looked at, rather than only
    # by being asserted in the capture tests.
    capture_log.append(capture_log.CHECK, todo_many, line=1, day=day(-8), ts=stamp(-8, 9))

    tally["capture_events"] = len(capture_log.read_all()[0])
    tally["entries"] = len(entries)
    tally["folders"] = len(folders) - 1  # scratch was deleted

    # ── does it actually load? ────────────────────────────────────────────
    #
    # The generator is only worth having if its output is known-good, and the
    # index is rebuilt from the log at launch anyway — so building it here is
    # the same work done early, where a bad fixture fails loudly instead of as
    # an empty screen.
    store = Store()
    store.start()
    tally["indexed_entries"] = len(store.entries(limit=500))
    tally["indexed_folders"] = len(store.folders())
    tally["due_reminders"] = len(store.due_reminders())
    tally["days"] = len(store.dates())
    store.close()

    if tally["indexed_entries"] != tally["entries"]:
        raise SystemExit(
            f"wrote {tally['entries']} entries and the index found "
            f"{tally['indexed_entries']} — the fixture is not valid"
        )
    return tally


def main() -> None:
    from datetime import date

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out",
        default=str(ROOT / "data.fixture"),
        help="where to build it (default: data.fixture/, which is gitignored)",
    )
    parser.add_argument(
        "--anchor",
        default=date.today().isoformat(),
        help="the day the fixture calls today (default: today). Pin it when a "
             "reproducible run is wanted; leave it alone for UI work, since "
             "due reminders are relative to it.",
    )
    parser.add_argument(
        "--force", action="store_true", help="rebuild an existing fixture directory"
    )
    args = parser.parse_args()

    try:
        datetime.strptime(args.anchor, "%Y-%m-%d")
    except ValueError:
        raise SystemExit(f"--anchor must be YYYY-MM-DD (got {args.anchor!r})")

    target = resolve_target(args.out, args.force)

    # Set before anything under `backend/` is imported: both `config` modules
    # read the environment at import time, which is the same contract
    # `conftest.py` relies on.
    os.environ["PGS_DATA_DIR"] = str(target)
    os.environ["PGS_CAPTURE_INDEX_PATH"] = str(target / "capture" / "index.sqlite")

    tally = build(target, args.anchor)

    print(f"built {target}")
    for key in ("capture_events", "entries", "days", "folders", "media",
                "due_reminders"):
        print(f"  {key:<16} {tally.get(key)}")
    print()
    print(f"  python desktop.py --data-dir {target}")
    print(f"  PGS_DATA_DIR={target} python -m uvicorn backend.app.main:app --port 8788")


if __name__ == "__main__":
    main()
